config/routes.rb
Rails.application.routes.draw do
  root to: 'cocktails#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cocktails do
    resources :doses
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  validates :name, presence: true, uniqueness: true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient
  validates :description, presence: true
  validates :cocktail, uniqueness: { scope: :ingredient }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  has_many :cocktails, through: :doses
  validates :name, presence: true, uniqueness: true

  def self.list_names
    pluck(:name).sort
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  before_action :set_cocktail, only: [:show, :edit, :update, :destroy]

  def index
    @cocktails = Cocktail.all
  end

  def show
  end

  def new
    @cocktail = Cocktail.new
  end

 # POST /cocktails
  # POST /cocktails.json
  def create
    @cocktail = Cocktail.new(cocktail_params)
     respond_to do |format|
      if @cocktail.save
        format.html { redirect_to @cocktail, notice: 'cocktail was successfully created.' }
      else
        format.html {render :new }
      end
    end
  end

  def edit
      # @cocktail = cocktail.find(params[:id])
  end

  # PATCH/PUT /cocktails/1
  # PATCH/PUT /cocktails/1.json
  def update
    respond_to do |format|
      if @cocktail.update(cocktail_params)
        format.html { redirect_to @cocktail, notice: 'cocktail was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @cocktail.destroy
    respond_to do |format|
      format.html { redirect_to cocktails_url, notice: 'cocktail was successfully destroyed.' }
    end
  end
private
  def cocktail_params
    params.require(:cocktail).permit(:name)
  end

  def set_cocktail
    @cocktail = Cocktail.find(params[:id])
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new
  end
 # POST /doses
  # POST /doses.json
  def create
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new(dose_params)
    @dose.cocktail = @cocktail
    if @dose.save
     redirect_to @cocktail
    else
      render :new
    end
  end

  # PATCH/PUT /doses/1
  # PATCH/PUT /doses/1.json

  # DELETE /doses/1
  # DELETE /doses/1.json
  def edit
      # @cocktail = cocktail.find(params[:id])
      raise
  end

  def destroy
    @dose.destroy
    respond_to do |format|
      format.html { redirect_to doses_url, notice: 'dose was successfully destroyed.' }
    end
  end

  private
    def dose_params
      params.require(:dose).permit(:description, :ingredient_id)
    end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  before_action :set_ingredient, only: [:show, :edit, :update, :destroy]

  def index
    @ingredients = Ingredient.all
  end

  def show
    @ingredient = Ingredient.find(params[:id])
  end
 # POST /ingredients
  # POST /ingredients.json
  def create
    @ingredient = Ingredient.new(ingredient_params)
     respond_to do |format|
      if @ingredient.save
        format.html { redirect_to @ingredient, notice: 'ingredient was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # DELETE /ingredients/1
  # DELETE /ingredients/1.json
  def destroy
    @ingredient.destroy
    respond_to do |format|
      format.html { redirect_to ingredients_url, notice: 'ingredient was successfully destroyed.' }
    end
  end


  private
  def ingredient_params
    params.require(:ingredient).permit(:name)
  end

  def set_ingredient
    @ingredient = Ingredient.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/views/cocktails/_form.html.erb
<%= simple_form_for (@cocktail) do |f| %>
  <%= f.input :name %>
  <%= f.submit "Add Cocktail", class: "btn btn-primary" %>
<% end %>

app/views/cocktails/edit.html.erb
<h1>Upgrade Cocktail</h1>

<%= render "form" %>
 <%= link_to 'Back', cocktails_path  %>

app/views/cocktails/index.html.erb
<h1>Cocktails</h1>
<ul>
<% @cocktails.each do |cocktail| %>
<li>
  <%= cocktail.name %>
<%= link_to 'Edit',  new_cocktail_path(cocktail)  %>
<%= link_to 'Show',  cocktail_path(cocktail)  %>
<%= link_to 'Destroy',  cocktail_path(cocktail), method: :delete %>
<%= link_to 'Add a dose',  new_cocktail_dose_path(cocktail)%>
</li>
<% end %>
</ul>
<%= link_to "Create you cocktail!", new_cocktail_path %>

app/views/cocktails/new.html.erb
<h1>New Cocktail</h1>

<%= render "form" %>
 <%= link_to 'Back', cocktails_path  %>

app/views/cocktails/show.html.erb
<h1><%= @cocktail.name %></h1>

<div id="ingredient">
  <h4>Ingredient</h4>
  <div class="ingredeient">
<% @cocktail.doses.each do |dose| %>
  <li>
    <div class="ingredient_name">
      <%= dose.ingredient.name %>
    </div>
    <div class="ingredient_description">
      <%= dose.description %>
    </div>
    <div class="add-in">
      <%= link_to 'Edit Ingredient',  edit_cocktail_path(@cocktail)  %>
      <%= link_to 'Delete Ingredients', cocktail_dose_path(@cocktail), method: :delete, data: { confirm: "Are you sure?" }, class: "card-remove-link" %>
      <% end %>
    </li>
  </div>
 </div>
</div>


<%= link_to 'Add ingredient',  new_cocktail_dose_path(@cocktail) %>

 <%= link_to 'Back', cocktails_path  %>

app/views/doses/edit.html.erb
<h1>Edit Dose</h1>
<div class="container">
  <h1>Edit  your ingredient and a description </h1>
  <div class="row">
    <div class="col-sm-6">
      <%= simple_form_for([@cocktail, @dose]) do |f| %>
        <%= f.association :ingredient %>
          <%= f.input :description %>
        <%= f.submit "Edit Dose", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>
 <%= link_to 'Back', cocktails_path  %>

app/views/doses/new.html.erb
<h1>New Dose</h1>
<div class="container">
  <h1>Add your ingredient and a description </h1>
  <div class="row">
    <div class="col-sm-6">
      <%= simple_form_for([@cocktail, @dose]) do |f| %>
        <%= f.association :ingredient %>
          <%= f.input :description %>
        <%= f.submit "Add Dose", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>
 <%= link_to 'Back', cocktails_path  %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <%= javascript_include_tag "application" %> <!-- from app/assets/javascripts/application.js -->
    <%= javascript_pack_tag "application" %>    <!-- from app/javascript/packs/application.js -->
  </body>
</html>